### ISSUE TITLE
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16

### ISSUE THREAD

**Issue by oanamariabalaita** [snow-actions/qrcode#28]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: r0adkll/sign-android-release@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by SnowCait** [comment]
Thanks.
Fixed by #27 and released [v1.1.0](https://github.com/snow-actions/qrcode/releases/tag/v1.1.0)
